### ISSUE TITLE
With the update to Android 11 the connection to the NAS started to abort or time out

### ISSUE THREAD

**Issue by kronwiz** [Sentaroh/SMBSync2#238]
SMBSync2 worked as a charm on my Samsung Galaxy A50 with Android 10, but after the update to Android 11 the connection to the NAS started to abort or time out.
My NAS supports only SMB1, so trying with more recent versions of the protocol doesn't solve the problem.
This happens also on another A50 phone, and even on a A52 which comes with Android 11 preinstalled. Thus it seems related to Android 11 and, probably, my old NAS.
I attach one of the logs files where you can see which are the error messages in detail.
Ofter the process ends with success but it lasts hours instead of minutes. Sometimes it fails.

[error.zip](https://github.com/Sentaroh/SMBSync2/files/6499068/error.zip)

**Comment by kronwiz** [comment]
Sorry, clicked the wrong button.

**Comment by Sentaroh** [comment]
Hi,

Sorry for late response.

Is the result the same even if I change the value of Timeout? (Default 30 Sec)
![image](https://user-images.githubusercontent.com/4037866/121980174-767c2c00-cdc6-11eb-8cae-5a6972160f0f.png)

Best regards.

**Comment by kronwiz** [comment]
Hi,

I changed the timeout to 60 and then to 120 seconds and let it run for a few days but it seems that the behaviour doesn't change: it succeeds for 2 days, then it fails for 1 day, then maybe it succeeds again, but it takes a long time and in the logs I see a lot of timeouts during the process.
To be sure that the smbd on the NAS wasn't blocked I killed it to start afresh, but even this doesn't change the result.

Thanks!

**Comment by Sentaroh** [comment]
Hi,

Please follow the steps in the link below to get the log and send it to us.
https://sentaroh.github.io/Documents/SMBSync2/SMBSync2_Log_EN.htm
1. Enable logging by above link.
2. Perform sync for reproduce error.
3. Send a log by above link.

Best regards.

**Comment by Sentaroh** [comment]
Hi,

From the log, it seems that the connection is blocked from the SMB server.
Isn't the process terminated due to lack of resources on the SMB server side?

> D I 2021/06/28 01:00:14.818 SyncThread       isFileChangedForLocalToRemote UTC        target=2019/07/13 15:31:29, master=2019/07/13 15:31:29
M E 2021/06/28 01:41:16.298 SyncThread       Backup-to-NAS: putErrorMessageJcifs From=/storage/emulated/0/Pictures/captain_marvel_poster_2.jpg, To=smb://192.168.1.10/Arda/Backup/A50A/Pictures/captain_marvel_poster_2.jpg 
M E 2021/06/28 01:41:16.299 SyncThread       Backup-to-NAS: Transport1[0.0.0.0<00>/192.168.1.10:445] timedout waiting for response to Trans2QueryPathInformation[command=SMB_COM_TRANSACTION2,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=1,pid=34143,uid=100,mid=786,wordCount=15,byteCount=107,totalParameterCount=106,totalDataCount=0,maxParameterCount=2,maxDataCount=40,maxSetupCount=0,flags=0x00,timeout=0,parameterCount=106,parameterOffset=66,parameterDisplacement=0,dataCount=0,dataOffset=172,dataDisplacement=0,setupCount=1,pad=1,pad1=0,informationLevel=0x101,filename=\Backup\A50A\Pictures\captain_marvel_poster_2.jpg] 
M E 2021/06/28 01:41:16.299 SyncThread       Backup-to-NAS: NT Status=0xc0000001 
D I 2021/06/28 01:41:16.301 JCIFS-V1         java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
M E 2021/06/28 01:41:16.302 SyncThread       Backup-to-NAS:  
M E 2021/06/28 01:41:16.304 SyncThread       Backup-to-NAS: com.sentaroh.jcifs.JcifsFile.exists(JcifsFile.java:178)
com.sentaroh.android.SMBSync2.SyncThread.isFileChangedForLocalToRemote(SyncThread.java:2869)
com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyInternalToSmb(SyncThreadSyncFile.java:1399)
com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyInternalToSmb(SyncThreadSyncFile.java:1276)
com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyInternalToSmb(SyncThreadSyncFile.java:1280)
com.sentaroh.android.SMBSync2.SyncThreadSyncFile.syncMirrorInternalToSmb(SyncThreadSyncFile.java:1224)
com.sentaroh.android.SMBSync2.SyncThread.performSync(SyncThread.java:1192)
com.sentaroh.android.SMBSync2.SyncThread.run(SyncThread.java:326) 
D I 2021/06/28 01:41:16.309 JCIFS-V1         	at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:283)
D I 2021/06/28 01:41:16.309 JCIFS-V1         	at java.net.AbstractPlainSocketImpl.shutdownOutput(AbstractPlainSocketImpl.java:636)
D I 2021/06/28 01:41:16.309 JCIFS-V1         	at java.net.Socket.shutdownOutput(Socket.java:1600)
D I 2021/06/28 01:41:16.310 JCIFS-V1         	at jcifs.smb.SmbTransport.doDisconnect(SmbTransport.java:369)
D I 2021/06/28 01:41:16.310 JCIFS-V1         	at jcifs.util.transport.Transport.disconnect(Transport.java:213)
D I 2021/06/28 01:41:16.310 JCIFS-V1         	at jcifs.util.transport.Transport.loop(Transport.java:122)
D I 2021/06/28 01:41:16.310 JCIFS-V1         	at jcifs.util.transport.Transport.run(Transport.java:267)
D I 2021/06/28 01:41:16.310 JCIFS-V1         	at java.lang.Thread.run(Thread.java:923)
D I 2021/06/28 01:41:16.311 JCIFS-V1         Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
D I 2021/06/28 01:41:16.311 JCIFS-V1         	at libcore.io.Linux.shutdown(Native Method)
D I 2021/06/28 01:41:16.311 JCIFS-V1         	at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:215)
D I 2021/06/28 01:41:16.312 JCIFS-V1         	at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:215)
D I 2021/06/28 01:41:16.312 JCIFS-V1         	at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:281)
D I 2021/06/28 01:41:16.312 JCIFS-V1         	... 7 more

Best regards.

**Comment by kronwiz** [comment]
Hello,

I looked at the SMB logs in the NAS and this is what I found:

> [2021/06/29 03:35:27,  1] smbd/service.c:make_connection_snum(1198)
  jcifs0_1_72 (::ffff:192.168.1.225) connect to service Arda initially as user nobody (uid=99, gid=1000) (pid 20003)
[2021/06/29 03:35:35,  0] lib/util_sock.c:read_socket_with_timeout(939)
[2021/06/29 03:35:35,  0] lib/util_sock.c:get_peer_addr_internal(1676)
  getpeername failed. Error was Transport endpoint is not connected
  read_socket_with_timeout: client 0.0.0.0 read error = Transport endpoint is not connected.
[2021/06/29 03:35:35,  1] smbd/service.c:close_cnum(1409)
  jcifs0_1_72 (::ffff:192.168.1.225) closed connection to service Arda

It's not the same day as the log in your comment above but this repeats more or less the same every day.

What I see is that first there's the connection from the client then, after a few seconds there's a timeout and then the server closes the connection on its side. On the application side the ENOTCONN error is raised after 2 minutes, when the timeout expires.
I haven't found yet the reason for the server's behaviour (for example, there are no hanging dead connections), but in my opinion what we found so far shows this is not a problem in your application.

So, if you agree, I can close this issue to avoid to waste more of your time and I will go on debugging the server by myself since now I also know where to look for smbsync2 detailed logs.
