### ISSUE TITLE
smbsync2 2.53 java.util.MissingFormatArgumentException

### ISSUE THREAD

**Issue by gv74** [Sentaroh/SMBSync2#243]
```
2021/06/16 12:22:18 dummy
Error
Copied:0 Deleted:0 Ignored:0.
java.util.MissingFormatArgumentException: Format specifier '%2$s'
 at java.util.Formatter.format(Formatter.java:2528)
 at java.util.Formatter.format(Formatter.java:2458)
 at java.lang.String.format(String.java:2883)
 at android.content.res.Resources.getString(Resources.java:548)
 at android.content.Context.getString(Context.java:598)
 at com.sentaroh.android.SMBSync2.SyncThread.isValidFileNameLength(SyncThread.java:899)
 at com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyExternalToSmb(SyncThreadSyncFile.java:2039)
 at com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyExternalToSmb(SyncThreadSyncFile.java:1973)
 at com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyExternalToSmb(SyncThreadSyncFile.java:1977)
 at com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyExternalToSmb(SyncThreadSyncFile.java:1977)
 at com.sentaroh.android.SMBSync2.SyncThreadSyncFile.moveCopyExternalToSmb(SyncThreadSyncFile.java:1977)
 at com.sentaroh.android.SMBSync2.SyncThreadSyncFile.syncMirrorExternalToSmb(SyncThreadSyncFile.java:1926)
 at com.sentaroh.android.SMBSync2.SyncThread.performSync(SyncThread.java:1430)
 at com.sentaroh.android.SMBSync2.SyncThread.run(SyncThread.java:326)
getSdcardRootPath=/storage/XXXX-XXXX
getUsbRootPath=/unknown_usb
ExternalFilesDirs=/storage/emulated/0/Android/data/com.sentaroh.android.SMBSync2/files
ExternalFilesDirs=/storage/XXXX-XXXX/Android/data/com.sentaroh.android.SMBSync2/files
getSdcardSafFile name=XXXX-XXXX

```

**Comment by Sentaroh** [comment]
Hi,

A fixed version has been uploaded to Google Play.
The same APK has been uploaded to the release. (https://github.com/Sentaroh/SMBSync2/releases/tag/Ver2.54)

Best regards.

**Comment by gv74** [comment]
Thank you.
